name: 趣头条

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【趣头条】'
        run: |
          node qtt.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          SENKU_SIGNKEY_QTT: ${{ secrets.SENKU_SIGNKEY_QTT }}
          SENKU_SIGNXTK_QTT: ${{ secrets.SENKU_SIGNXTK_QTT }}
          SENKU_READKEY_QTT: ${{ secrets.SENKU_READKEY_QTT }}
          SENKU_NAVCOINKEY_QTT: ${{ secrets.SENKU_NAVCOINKEY_QTT }}
